export class configData{

	smsEdit:any = {
		'drivername':'',
		'driverdata':[],
		'templateid':''
	}

	smsDriverData:any = {
		"alidayu":{
            "base":{
                "real_name":"阿里大鱼",
                "url":"https://www.alidayu.com/"
            },
            "value":[
                {"name":"app_key","value":"","valid":true},
                {"name":"app_secret","value":"","valid":true},
                {"name":"sign_name","value":"","valid":true}
            ]
        },
        "yunpian":{
            "base":{
                "real_name":"云片",
                "url":"https://www.yunpian.com/"
            },
            "value":[
                {"name":"api_key","value":"","valid":true}
            ]
        },
        "submail":{
            "base":{
                "real_name":"赛邮云通讯",
                "url":"https://www.mysubmail.com/"
            },
            "value":[
                {"name":"app_id","value":"","valid":true},
                {"name":"app_key","value":"","valid":true}
            ]
        },
        "luosimao":{
            "base":{
                "real_name":"螺丝帽",
                "url":"https://luosimao.com/"
            },
            "value":[
                {"name":"api_key","value":"","valid":true}
            ]
        },
        "yuntongxun":{
            "base":{
                "real_name":"容联云通讯",
                "url":"http://www.yuntongxun.com/"
            },
            "value":[
                {"name":"app_id","value":"","valid":true},
                {"name":"account_sid","value":"","valid":true},
                {"name":"account_token","value":"","valid":true},
                {"name":"is_sub_account","value":false,"valid":true}
            ]
        },
        "huyi":{
            "base":{
                "real_name":"互亿无线",
                "url":"http://www.ihuyi.com/"
            },
            "value":[
                {"name":"api_id","value":"","valid":true},
                {"name":"api_key","value":"","valid":true},
            ]
        },
        "juhe":{
            "base":{
                "real_name":"聚合数据",
                "url":"https://www.juhe.cn/"
            },
            "value":[
                {"name":"app_key","value":"","valid":true}
            ]
        },
        "sendcloud":{
            "base":{
                "real_name":"SendCloud",
                "url":"http://www.sendcloud.net/"
            },
            "value":[
                {"name":"sms_user","value":"","valid":true},
                {"name":"sms_key","value":"","valid":true}
            ]
        },
        "baidu":{
            "base":{
                "real_name":"百度云",
                "url":"https://cloud.baidu.com/"
            },
            "value":[
                {"name":"ak","value":"","valid":true},
                {"name":"sk","value":"","valid":true},
                {"name":"invoke_id","value":"","valid":true},
                {"name":"domain","value":"","valid":true}
            ]
        }   
	}
}