export class testRole{
	data:any[] = [
        {
            "id":4,
            "name":"项目管理",
            "app_name":"项目管理",
            "model":"Project",
            "isCheck":false,
            "parentid":0,
            "level":0,
            "chilren":[
                {
                    "id":46,
                    "model":"Project",
                    "parentid":0,
                    "path":"api/project/setting",
                    "url":"setting",
                    "name":"基本设置",
                    "fonticon":"",
                    "type":1,
                    "status":1,
                    "sort":0,
                    "isdel":2,
                    "is_left":3,
                    "cid":1,
                    "version":0,
                    "level":1,
                    "isCheck":false,
                    "parent_path":"",
                    "app_name":"项目管理",
                    "chilren":[

                    ]
                },
                {
                    "id":47,
                    "model":"Project",
                    "parentid":0,
                    "path":"api/project/task_template",
                    "url":"task_template",
                    "name":"任务模板",
                    "fonticon":"",
                    "type":1,
                    "status":1,
                    "sort":0,
                    "isdel":2,
                    "is_left":3,
                    "cid":1,
                    "version":0,
                    "level":1,
                    "isCheck":false,
                    "parent_path":"",
                    "app_name":"项目管理",
                    "chilren":[
                        {
                            "id":55,
                            "model":"Project",
                            "parentid":47,
                            "path":"api/project/task/add_tem",
                            "url":"task/add_tem",
                            "name":"添加模板",
                            "fonticon":"",
                            "type":1,
                            "status":1,
                            "sort":0,
                            "isdel":2,
                            "is_left":3,
                            "cid":1,
                            "version":0,
                            "level":2,
                            "isCheck":false,
                            "parent_path":"api/project/task_template",
                            "app_name":"项目管理",
                            "chilren":[
		                        {
		                            "id":550,
		                            "model":"Project",
		                            "parentid":55,
		                            "path":"api/project/task/add_tem",
		                            "url":"task/add_tem",
		                            "name":"添加模板",
		                            "fonticon":"",
		                            "type":1,
		                            "status":1,
		                            "sort":0,
		                            "isdel":2,
		                            "is_left":3,
		                            "cid":1,
		                            "version":0,
		                            "level":3,
		                            "isCheck":false,
		                            "parent_path":"api/project/task_template",
		                            "app_name":"项目管理子1",
		                            "chilren":[

		                            ]
		                        },
		                        {
		                            "id":551,
		                            "model":"Project",
		                            "parentid":55,
		                            "path":"api/project/task/add_tem",
		                            "url":"task/add_tem",
		                            "name":"添加模板",
		                            "fonticon":"",
		                            "type":1,
		                            "status":1,
		                            "sort":0,
		                            "isdel":2,
		                            "is_left":3,
		                            "cid":1,
		                            "version":0,
		                            "level":3,
		                            "isCheck":false,
		                            "parent_path":"api/project/task_template",
		                            "app_name":"项目管理子2",
		                            "chilren":[
				                        {
				                            "id":5511,
				                            "model":"Project",
				                            "parentid":551,
				                            "path":"api/project/task/add_tem",
				                            "url":"task/add_tem",
				                            "name":"添加模板",
				                            "fonticon":"",
				                            "type":1,
				                            "status":1,
				                            "sort":0,
				                            "isdel":2,
				                            "is_left":3,
				                            "cid":1,
				                            "version":0,
				                            "level":3,
				                            "isCheck":false,
				                            "parent_path":"api/project/task_template",
				                            "app_name":"项目管理子2-3",
				                            "chilren":[

				                            ]
				                        }
		                            ]
		                        },
		                        {
		                            "id":552,
		                            "model":"Project",
		                            "parentid":55,
		                            "path":"api/project/task/add_tem",
		                            "url":"task/add_tem",
		                            "name":"添加模板",
		                            "fonticon":"",
		                            "type":1,
		                            "status":1,
		                            "sort":0,
		                            "isdel":2,
		                            "is_left":3,
		                            "cid":1,
		                            "version":0,
		                            "level":3,
		                            "isCheck":false,
		                            "parent_path":"api/project/task_template",
		                            "app_name":"项目管理子3",
		                            "chilren":[

		                            ]
		                        }
                            ]
                        },
                        {
                            "id":58,
                            "model":"Project",
                            "parentid":47,
                            "path":"api/project/task/edit_tem",
                            "url":"task/edit_tem",
                            "name":"修改模板",
                            "fonticon":"console-edit",
                            "type":1,
                            "status":1,
                            "sort":0,
                            "isdel":2,
                            "is_left":3,
                            "cid":1,
                            "version":0,
                            "level":2,
                            "isCheck":false,
                            "parent_path":"api/project/task_template",
                            "app_name":"项目管理",
                            "chilren":[

                            ]
                        }
                    ]
                },
                {
                    "id":48,
                    "model":"Project",
                    "parentid":0,
                    "path":"api/project/role",
                    "url":"role",
                    "name":"权限设置",
                    "fonticon":"",
                    "type":1,
                    "status":1,
                    "sort":0,
                    "isdel":2,
                    "is_left":3,
                    "cid":1,
                    "version":0,
                    "level":1,
                    "isCheck":false,
                    "parent_path":"",
                    "app_name":"项目管理",
                    "chilren":[
		                {
		                    "id":480,
		                    "model":"Project",
		                    "parentid":48,
		                    "path":"api/project/role",
		                    "url":"role",
		                    "name":"权限设置",
		                    "fonticon":"",
		                    "type":1,
		                    "status":1,
		                    "sort":0,
		                    "isdel":2,
		                    "is_left":3,
		                    "cid":1,
		                    "version":0,
		                    "level":1,
		                    "isCheck":false,
		                    "parent_path":"",
		                    "app_name":"权限设置1",
		                    "chilren":[
				                {
				                    "id":4801,
				                    "model":"Project",
				                    "parentid":480,
				                    "path":"api/project/role",
				                    "url":"role",
				                    "name":"权限设置",
				                    "fonticon":"",
				                    "type":1,
				                    "status":1,
				                    "sort":0,
				                    "isdel":2,
				                    "is_left":3,
				                    "cid":1,
				                    "version":0,
				                    "level":1,
				                    "isCheck":false,
				                    "parent_path":"",
				                    "app_name":"权限设置1-2",
				                    "chilren":[

				                    ]
				                }
		                    ]
		                }
                    ]
                },
                {
                    "id":49,
                    "model":"Project",
                    "parentid":0,
                    "path":"api/project/user",
                    "url":"user",
                    "name":"成员管理",
                    "fonticon":"",
                    "type":1,
                    "status":1,
                    "sort":0,
                    "isdel":2,
                    "is_left":3,
                    "cid":1,
                    "version":0,
                    "level":1,
                    "isCheck":false,
                    "parent_path":"",
                    "app_name":"项目管理",
                    "chilren":[

                    ]
                }
            ]
        }

	]
}